name: Build

on:
  push:
    tags:
      - '*'

env:
  DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_IMAGE_TAG: ${{ vars.DOCKER_IMAGE_TAG }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Init Settings
        # language="Shell Script"
        run: |
          set_default_env_var() { if [ -z "${!1}" ]; then echo "$1=$2" >> $GITHUB_ENV; fi }
          set_default_env_var 'DOCKER_REGISTRY' 'ghcr.io'
          set_default_env_var 'DOCKER_USERNAME' '${{ github.actor }}'
          set_default_env_var 'DOCKER_PASSWORD' '${{ secrets.GITHUB_TOKEN }}'
          set_default_env_var 'DOCKER_IMAGE_TAG' "ghcr.io/muxiu1997/docker-restic-rclone-deno"
    
      - name: Parse Versions
        # language="Shell Script"
        run: |
          set -e
          TAG_NAME=${GITHUB_REF#refs/tags/}
          RESTIC_VERSION=""
          RCLONE_VERSION=""
          DENO_VERSION=""
          
          if [[ $TAG_NAME =~ ^restic-([^+]+)\+rclone-([^+]+)\+deno-(.+)$ ]]; then
            RESTIC_VERSION="${BASH_REMATCH[1]}"
            RCLONE_VERSION="${BASH_REMATCH[2]}"
            DENO_VERSION="${BASH_REMATCH[3]}"
          else
            echo "Error: Invalid tag format"
            echo "Expected format: restic-VERSION+rclone-VERSION+deno-VERSION"
            echo "Example: restic-0.18.0+rclone-1.71.0+deno-2.4.5"
            echo "Actual: $TAG_NAME"
            exit 1
          fi
          
          echo "RESTIC_VERSION=$RESTIC_VERSION" >> $GITHUB_ENV
          echo "RCLONE_VERSION=$RCLONE_VERSION" >> $GITHUB_ENV
          echo "DENO_VERSION=$DENO_VERSION" >> $GITHUB_ENV
          
          echo "DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG}:restic${RESTIC_VERSION}-rclone${RCLONE_VERSION}-deno${DENO_VERSION}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}

      # region Docker
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          push: true
          build-args: |
            RESTIC_VERSION=${{ env.RESTIC_VERSION }}
            RCLONE_VERSION=${{ env.RCLONE_VERSION }}
            DENO_VERSION=${{ env.DENO_VERSION }}
          tags: ${{ env.DOCKER_IMAGE_TAG }}